"""clean removal of tournament, matchplayers, otp  models

Revision ID: 81c2b4cc1208
Revises: ae871e2f6ac1
Create Date: 2026-04-30 16:14:53.550932

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "81c2b4cc1208"
down_revision = "ae871e2f6ac1"
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table("users")
    op.drop_table("matches")
    op.drop_table("leaderboard")
    op.drop_table("match_players")
    op.drop_table("tournaments")
    op.drop_table("otp")
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("username", sa.String(20), nullable=False),
        sa.Column("email", sa.String(120), nullable=False),
        sa.Column("password_hash", sa.String(60), nullable=False),
        sa.Column("profile_pic", sa.String(225), nullable=False),
        sa.Column("elo", sa.Integer(), nullable=False),
    )

    op.create_index("ix_users_username", "users", ["username"], unique=True)
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("match_code", sa.String(4), unique=True),
        sa.Column("player1_id", sa.Integer(), sa.ForeignKey("users.id")),
        sa.Column("player2_id", sa.Integer(), sa.ForeignKey("users.id")),
        sa.Column("winner_id", sa.Integer(), sa.ForeignKey("users.id")),
        sa.Column("player1_elo", sa.Integer()),
        sa.Column("player2_elo", sa.Integer()),
        sa.Column("created_at", sa.DateTime(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("matches")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
